### ISSUE TITLE
Bug in scope

### ISSUE THREAD

**Issue by ramezrafla** [wt/gatsby-plugin-google-gapi#1]
Hello

Thanks for this plugin

In gatsby-ssr you join the scopes without quotes around each scope
Likely you didn't test it with more than one scope

**Comment by wt** [comment]
Thanks for reporting this bug. Would you be willing to write up a PR? I'd be happy to merge it. Otherwise, it may take me some time to get to this.

**Comment by wt** [comment]
https://github.com/wt/gatsby-plugin-google-gapi/blob/master/gatsby-ssr.js#L51 <-- this looks like the possible place to fix
